# fly.toml app configuration file generated for whosit-client on 2024-02-04T05:09:37-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "whosit-client"
primary_region = "ewr"

[build]

[env]
  SERVER_URL = "whosit-server.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
